// Wire Protocol Manifest
//
// Generated by scripts/gen-wire-manifest.mts — do not edit by hand.
// Regenerate with: pnpm --filter @moonshot-ai/agent-core-v2 gen:wire-manifest
//
// protocol_version: "1.5" (migrations: 1.0 -> 1.1 -> 1.2 -> 1.3 -> 1.4 -> 1.5)
//
// One declaration per durable record type — an Event2 subclass declaring
// `static type` + `static durable = true` + `static schema` — drained from the
// runtime EVENT2_REGISTRY ("import = register"). Every payload declaration
// carries its record type in a `_name` field. Payload sketches use TypeScript
// type syntax; when a named type is expanded inline, its name appears as a doc
// comment (`/** ContextMessage */`). Bare type names (ContentPart,
// ContextMessage, …) refer to the real types in src/ — they are intentionally
// not resolved here. `// …` marks a capped field list. On disk (wire.jsonl)
// the journal opens with a metadata line {"type": "metadata",
// "protocol_version", "created_at"}; each record is {"type", ...payload,
// "time"} — object payloads spread at the top level.
//
// Every listed type is durable by construction — transient Event2 classes
// never enter EVENT2_REGISTRY, so there is no persisted flag. Declaration
// header lines: states (every state folding this record type on dispatch and
// replay; any state beyond the first is what the retired format listed as
// cross-reducers), blobs (the folding states whose blob codec offloads inline
// media to blob storage), owner (the source file declaring the class).

// Index (48 record types)
//   config.update                      profile                                                               src/agent/profile/profileOps.ts
//   context.append_loop_event          contextMemory, turn                                                   src/agent/contextMemory/contextEvents.ts
//   context.append_message             contextMemory, goalForkNotice, plan, task.notificationDelivery, todo  src/agent/contextMemory/contextEvents.ts
//   context.apply_compaction           contextMemory, plan, task.notificationDelivery, todo                  src/agent/contextMemory/contextEvents.ts
//   context.clear                      contextMemory, plan, task.notificationDelivery, todo                  src/agent/contextMemory/contextEvents.ts
//   context.undo                       contextMemory, plan, task.notificationDelivery, todo                  src/agent/contextMemory/contextEvents.ts
//   forked                             goal, goalForkNotice                                                  src/agent/goal/goalOps.ts
//   full_compaction.begin              fullCompaction                                                        src/agent/fullCompaction/compactionOps.ts
//   full_compaction.cancel             fullCompaction                                                        src/agent/fullCompaction/compactionOps.ts
//   full_compaction.complete           fullCompaction                                                        src/agent/fullCompaction/compactionOps.ts
//   goal.clear                         goal, goalForkNotice                                                  src/agent/goal/goalOps.ts
//   goal.create                        goal, goalForkNotice                                                  src/agent/goal/goalOps.ts
//   goal.update                        goal                                                                  src/agent/goal/goalOps.ts
//   interaction.request                interaction                                                           src/session/interaction/interactionOps.ts
//   interaction.resolved               interaction                                                           src/session/interaction/interactionOps.ts
//   interruptionReminder.recorded      interruptionReminder                                                  src/agent/interruptionReminder/interruptionReminderOps.ts
//   llm.request                        llm.requestTrace                                                      src/agent/llmRequester/llmRequestOps.ts
//   llm.tools_snapshot                 llm.requestTrace                                                      src/agent/llmRequester/llmRequestOps.ts
//   mcp.tools_discovered               mcp.discovery                                                         src/agent/mcp/mcpDiscoveryOps.ts
//   permission.record_approval_result  permissionRules                                                       src/agent/permissionRules/permissionRulesOps.ts
//   permission.set_mode                permissionMode, permissionMode.configured                             src/agent/permissionMode/permissionModeOps.ts
//   plan_mode.cancel                   plan                                                                  src/features/plan/planOps.ts
//   plan_mode.enter                    plan                                                                  src/features/plan/planOps.ts
//   plan_mode.exit                     plan                                                                  src/features/plan/planOps.ts
//   plan.revision                      plan                                                                  src/features/plan/planOps.ts
//   plugin.session_start               pluginSessionStartSnapshot                                            src/agent/plugin/agentPluginOps.ts
//   profile.bind                       profile, profile.activeTools                                          src/agent/profile/profileOps.ts
//   prompt.accepted                    promptAdmission                                                       src/agent/prompt/promptOps.ts
//   runtime.set_binding                runtimeBinding                                                        src/agent/runtimeBinding/runtimeBindingOps.ts
//   swarm_mode.enter                   swarm                                                                 src/features/swarm/swarmOps.ts
//   swarm_mode.exit                    contextMemory, swarm                                                  src/features/swarm/swarmOps.ts
//   task.started                       task                                                                  src/agent/task/taskOps.ts
//   task.terminated                    task                                                                  src/agent/task/taskOps.ts
//   token_counting.measured            tokenCounting                                                         src/agent/tokenCounting/tokenCountingOps.ts
//   token_counting.rebased             tokenCounting                                                         src/agent/tokenCounting/tokenCountingOps.ts
//   token_counting.truncated           tokenCounting                                                         src/agent/tokenCounting/tokenCountingOps.ts
//   tools.register_user_tool           userTool                                                              src/agent/userTool/userToolOps.ts
//   tools.reset_active_tools           profile.activeTools                                                   src/agent/profile/profileOps.ts
//   tools.set_active_tools             profile.activeTools                                                   src/agent/profile/profileOps.ts
//   tools.unregister_user_tool         userTool                                                              src/agent/userTool/userToolOps.ts
//   tools.update_store                 todo                                                                  src/session/todo/todoOps.ts
//   tower_mode.enter                   tower                                                                 src/features/tower/towerOps.ts
//   tower_mode.exit                    tower                                                                 src/features/tower/towerOps.ts
//   turn.cancel                        turn                                                                  src/agent/loop/turnOps.ts
//   turn.ended                         turn                                                                  src/agent/loop/turnOps.ts
//   turn.prompt                        turn                                                                  src/agent/loop/turnOps.ts
//   turn.steer                         turn                                                                  src/agent/loop/turnOps.ts
//   usage.record                       usage                                                                 src/agent/usage/usageOps.ts

/**
 * states: profile
 * owner: src/agent/profile/profileOps.ts
 */
interface ConfigUpdatePayload {
  _name: 'config.update';
  modelAlias?: string;
  profileName?: string;
  /** ThinkingEffort */
  thinkingEffort?: 'off' | 'on' | (string & {});
  /** ThinkingEffort */
  thinkingLevel?: 'off' | 'on' | (string & {});
  systemPrompt?: string;
  /** EnvironmentDisclosureSnapshot */
  environmentDisclosure?: {
    cwd: string;
    date: { disclosed: true, value: { localDate: string, timeZone: string } } | { disclosed: false };
  };
  renderGeneration?: number;
  agentsMdPaths?: string[];
  disallowedTools?: string[];
}

/**
 * states: contextMemory, turn · blobs: contextMemory
 * owner: src/agent/contextMemory/contextEvents.ts
 */
interface ContextAppendLoopEventPayload {
  _name: 'context.append_loop_event';
  /** LoopRecordedEvent */
  event: 'step.begin' | 'step.end' | 'content.part' | 'tool.call' | 'tool.result';
}

/**
 * states: contextMemory, goalForkNotice, plan, task.notificationDelivery, todo · blobs: contextMemory
 * owner: src/agent/contextMemory/contextEvents.ts
 */
interface ContextAppendMessagePayload {
  _name: 'context.append_message';
  /** ContextMessage */
  message: {
    role: 'system' | 'user' | 'assistant' | 'tool';
    name?: string;
    content: ('text' | 'think' | 'image_url' | 'audio_url' | 'video_url')[];
    toolCalls: {
      type: 'function';
      id: string;
      name: string;
      arguments: string | null;
      extras?: Record<string, unknown>;
      _streamIndex?: number | string;
    }[];
    toolCallId?: string;
    partial?: boolean;
    tools?: {
      name: string;
      description: string;
      parameters: Record<string, unknown>;
      deferred?: true;
    }[];
    id?: string;
    providerMessageId?: string;
    origin?: 'user' | 'skill_activation' | 'plugin_command' | 'injection' | 'shell_command' | 'compaction_summary' | 'system_trigger' | 'task' | 'cron_job' | 'cron_missed' | 'hook_result' | 'retry' | undefined;
    isError?: boolean;
    note?: string;
  };
}

/**
 * states: contextMemory, plan, task.notificationDelivery, todo · blobs: contextMemory
 * owner: src/agent/contextMemory/contextEvents.ts
 * shared base: ...contextCompactionBaseShape
 */
type ContextApplyCompactionPayload = { _name: 'context.apply_compaction'; } & ({ summary: string, compactedCount: number, contextSummary?: string } | { contextSummary: string, compactedCount: number, summary?: string } | { summary: ContextMessage, count: number, compactedCount?: number });

/**
 * states: contextMemory, plan, task.notificationDelivery, todo · blobs: contextMemory
 * owner: src/agent/contextMemory/contextEvents.ts
 */
interface ContextClearPayload {
  _name: 'context.clear';
}

/**
 * states: contextMemory, plan, task.notificationDelivery, todo · blobs: contextMemory
 * owner: src/agent/contextMemory/contextEvents.ts
 */
interface ContextUndoPayload {
  _name: 'context.undo';
  count: number;
}

/**
 * states: goal, goalForkNotice
 * owner: src/agent/goal/goalOps.ts
 */
interface ForkedPayload {
  _name: 'forked';
}

/**
 * states: fullCompaction
 * owner: src/agent/fullCompaction/compactionOps.ts
 * payload type: CompactionBeginData
 */
interface FullCompactionBeginPayload {
  _name: 'full_compaction.begin';
  instruction?: string;
  source: 'manual' | 'auto';
}

/**
 * states: fullCompaction
 * owner: src/agent/fullCompaction/compactionOps.ts
 */
interface FullCompactionCancelPayload {
  _name: 'full_compaction.cancel';
}

/**
 * states: fullCompaction
 * owner: src/agent/fullCompaction/compactionOps.ts
 */
interface FullCompactionCompletePayload {
  _name: 'full_compaction.complete';
}

/**
 * states: goal, goalForkNotice
 * owner: src/agent/goal/goalOps.ts
 */
interface GoalClearPayload {
  _name: 'goal.clear';
}

/**
 * states: goal, goalForkNotice
 * owner: src/agent/goal/goalOps.ts
 */
interface GoalCreatePayload {
  _name: 'goal.create';
  goalId: string;
  objective: string;
  completionCriterion?: string;
  wallClockResumedAt?: number;
  status?: 'active' | 'paused' | 'blocked' | 'complete';
  actor?: 'user' | 'model' | 'runtime' | 'system';
  budgetLimits?: {
    tokenBudget?: number;
    turnBudget?: number;
    wallClockBudgetMs?: number;
  };
}

/**
 * states: goal
 * owner: src/agent/goal/goalOps.ts
 */
interface GoalUpdatePayload {
  _name: 'goal.update';
  goalId?: string;
  status?: 'active' | 'paused' | 'blocked' | 'complete';
  reason?: string;
  turnsUsed?: number;
  tokensUsed?: number;
  wallClockMs?: number;
  wallClockResumedAt?: number;
  budgetLimits?: {
    tokenBudget?: number;
    turnBudget?: number;
    wallClockBudgetMs?: number;
  };
  actor?: 'user' | 'model' | 'runtime' | 'system';
}

/**
 * states: interaction
 * owner: src/session/interaction/interactionOps.ts
 */
interface InteractionRequestPayload {
  _name: 'interaction.request';
  id: string;
  kind: 'approval' | 'question' | 'user_tool';
  toolCallId?: string;
  agentId?: string;
  request: any;
}

/**
 * states: interaction
 * owner: src/session/interaction/interactionOps.ts
 */
interface InteractionResolvedPayload {
  _name: 'interaction.resolved';
  id: string;
  response: any;
}

/**
 * states: interruptionReminder
 * owner: src/agent/interruptionReminder/interruptionReminderOps.ts
 */
interface InterruptionReminderRecordedPayload {
  _name: 'interruptionReminder.recorded';
  turnId: number;
}

/**
 * states: llm.requestTrace
 * owner: src/agent/llmRequester/llmRequestOps.ts
 */
interface LlmRequestPayload {
  _name: 'llm.request';
  kind: 'loop' | 'compaction';
  provider: string;
  model: string;
  modelAlias?: string;
  /** ThinkingEffort */
  thinkingEffort?: 'off' | 'on' | (string & {});
  thinkingKeep?: string;
  temperature?: number;
  topP?: number;
  maxTokens?: number;
  betaApi?: boolean;
  toolSelect: boolean;
  systemPromptHash: string;
  systemPrompt?: string;
  toolsHash: string;
  messageCount: number;
  turnStep?: string;
  attempt?: string;
  projection?: 'strict' | 'media-degraded' | 'media-stripped' | 'strict-media-degraded' | 'strict-media-stripped';
  droppedCount?: number;
}

/**
 * states: llm.requestTrace
 * owner: src/agent/llmRequester/llmRequestOps.ts
 */
interface LlmToolsSnapshotPayload {
  _name: 'llm.tools_snapshot';
  hash: string;
  tools: {
    name: string;
    description: string;
    parameters: Record<string, any>;
  }[];
}

/**
 * states: mcp.discovery
 * owner: src/agent/mcp/mcpDiscoveryOps.ts
 */
interface McpToolsDiscoveredPayload {
  _name: 'mcp.tools_discovered';
  serverName: string;
  hash: string;
  tools: readonly MCPToolDefinition[];
  enabledNames: string[];
  collisions?: {
    qualified: string;
    toolName: string;
    collidesWith: { kind: 'same_server', toolName: string } | { kind: 'other_server', serverName: string };
  }[];
}

/**
 * states: permissionRules
 * owner: src/agent/permissionRules/permissionRulesOps.ts
 * payload type: PermissionApprovalResultRecord
 */
interface PermissionRecordApprovalResultPayload {
  _name: 'permission.record_approval_result';
  turnId: number;
  toolCallId: string;
  toolName: string;
  action: string;
  sessionApprovalRule?: string;
  result: ApprovalResponse;
}

/**
 * states: permissionMode, permissionMode.configured
 * owner: src/agent/permissionMode/permissionModeOps.ts
 */
interface PermissionSetModePayload {
  _name: 'permission.set_mode';
  /** PermissionMode */
  mode: 'manual' | 'yolo' | 'auto';
}

/**
 * states: plan
 * owner: src/features/plan/planOps.ts
 */
interface PlanModeCancelPayload {
  _name: 'plan_mode.cancel';
  id?: string;
}

/**
 * states: plan
 * owner: src/features/plan/planOps.ts
 */
interface PlanModeEnterPayload {
  _name: 'plan_mode.enter';
  id: string;
}

/**
 * states: plan
 * owner: src/features/plan/planOps.ts
 */
interface PlanModeExitPayload {
  _name: 'plan_mode.exit';
  id?: string;
}

/**
 * states: plan
 * owner: src/features/plan/planOps.ts
 */
interface PlanRevisionPayload {
  _name: 'plan.revision';
  id: string;
  version: number;
  path: string;
  sha256: string;
  bytes: number;
}

/**
 * states: pluginSessionStartSnapshot
 * owner: src/agent/plugin/agentPluginOps.ts
 */
interface PluginSessionStartPayload {
  _name: 'plugin.session_start';
  content: string | null;
}

/**
 * states: profile, profile.activeTools
 * owner: src/agent/profile/profileOps.ts
 */
interface ProfileBindPayload {
  _name: 'profile.bind';
  modelAlias?: string;
  profileName?: string;
  /** ThinkingEffort */
  thinkingEffort: 'off' | 'on' | (string & {});
  systemPrompt: string;
  /** EnvironmentDisclosureSnapshot */
  environmentDisclosure?: {
    cwd: string;
    date: { disclosed: true, value: { localDate: string, timeZone: string } } | { disclosed: false };
  };
  renderGeneration?: number;
  agentsMdPaths?: string[];
  activeToolNames?: string[];
  disallowedTools: string[];
  subagents?: string[];
}

/**
 * states: promptAdmission
 * owner: src/agent/prompt/promptOps.ts
 */
interface PromptAcceptedPayload {
  _name: 'prompt.accepted';
  promptId: string;
}

/**
 * states: runtimeBinding
 * owner: src/agent/runtimeBinding/runtimeBindingOps.ts
 */
interface RuntimeSetBindingPayload {
  _name: 'runtime.set_binding';
  workspaceId: string;
  runtimeId: string;
}

/**
 * states: swarm
 * owner: src/features/swarm/swarmOps.ts
 */
interface SwarmModeEnterPayload {
  _name: 'swarm_mode.enter';
  /** SwarmModeTrigger */
  trigger: 'manual' | 'task' | 'tool';
}

/**
 * states: contextMemory, swarm · blobs: contextMemory
 * owner: src/features/swarm/swarmOps.ts
 */
interface SwarmModeExitPayload {
  _name: 'swarm_mode.exit';
}

/**
 * states: task
 * owner: src/agent/task/taskOps.ts
 */
interface TaskStartedPayload {
  _name: 'task.started';
  /** AgentTaskInfo */
  info: AgentTaskInfoByKind[AgentTaskKind];
}

/**
 * states: task
 * owner: src/agent/task/taskOps.ts
 */
interface TaskTerminatedPayload {
  _name: 'task.terminated';
  /** AgentTaskInfo */
  info: AgentTaskInfoByKind[AgentTaskKind];
  outputTail?: string;
}

/**
 * states: tokenCounting
 * owner: src/agent/tokenCounting/tokenCountingOps.ts
 */
interface TokenCountingMeasuredPayload {
  _name: 'token_counting.measured';
  length: number;
  tokens: number;
}

/**
 * states: tokenCounting
 * owner: src/agent/tokenCounting/tokenCountingOps.ts
 */
interface TokenCountingRebasedPayload {
  _name: 'token_counting.rebased';
  length: number;
  tokens: number;
  measured: boolean;
}

/**
 * states: tokenCounting
 * owner: src/agent/tokenCounting/tokenCountingOps.ts
 */
interface TokenCountingTruncatedPayload {
  _name: 'token_counting.truncated';
  length: number;
  tokens: number;
}

/**
 * states: userTool
 * owner: src/agent/userTool/userToolOps.ts
 * payload type: UserToolRegistration
 */
interface ToolsRegisterUserToolPayload {
  _name: 'tools.register_user_tool';
  name: string;
  description: string;
  parameters: Record<string, unknown>;
  disclosure?: 'inline' | 'deferred';
}

/**
 * states: profile.activeTools
 * owner: src/agent/profile/profileOps.ts
 */
interface ToolsResetActiveToolsPayload {
  _name: 'tools.reset_active_tools';
}

/**
 * states: profile.activeTools
 * owner: src/agent/profile/profileOps.ts
 */
interface ToolsSetActiveToolsPayload {
  _name: 'tools.set_active_tools';
  names: string[];
}

/**
 * states: userTool
 * owner: src/agent/userTool/userToolOps.ts
 */
interface ToolsUnregisterUserToolPayload {
  _name: 'tools.unregister_user_tool';
  name: string;
}

/**
 * states: todo
 * owner: src/session/todo/todoOps.ts
 */
interface ToolsUpdateStorePayload {
  _name: 'tools.update_store';
  key: string;
  value: any;
}

/**
 * states: tower
 * owner: src/features/tower/towerOps.ts
 */
interface TowerModeEnterPayload {
  _name: 'tower_mode.enter';
}

/**
 * states: tower
 * owner: src/features/tower/towerOps.ts
 */
interface TowerModeExitPayload {
  _name: 'tower_mode.exit';
}

/**
 * states: turn
 * owner: src/agent/loop/turnOps.ts
 */
interface TurnCancelPayload {
  _name: 'turn.cancel';
  turnId?: number;
  target?: 'active' | 'queued';
  reason?: 'user_cancelled' | 'aborted';
}

/**
 * states: turn
 * owner: src/agent/loop/turnOps.ts
 */
interface TurnEndedPayload {
  _name: 'turn.ended';
  turnId: number;
  reason: 'completed' | 'cancelled' | 'failed' | 'blocked';
  /** KimiErrorPayload */
  error?: {
    code: (typeof ErrorCodes)[keyof typeof ErrorCodes];
    message: string;
    name?: string;
    details?: Readonly<Record<string, unknown>>;
    retryable: boolean;
    cause?: {
      code: (typeof ErrorCodes)[keyof typeof ErrorCodes];
      message: string;
      name?: string;
      details?: Readonly<Record<string, unknown>>;
      retryable: boolean;
      cause?: {
        code: (typeof ErrorCodes)[keyof typeof ErrorCodes];
        message: string;
        name?: string;
        details?: Readonly<Record<string, unknown>>;
        retryable: boolean;
        cause?: {
          code: (typeof ErrorCodes)[keyof typeof ErrorCodes];
          message: string;
          name?: string;
          details?: Readonly<Record<string, unknown>>;
          retryable: boolean;
          cause?: {
            code: (typeof ErrorCodes)[keyof typeof ErrorCodes];
            message: string;
            name?: string;
            details?: Readonly<Record<string, unknown>>;
            retryable: boolean;
            cause?: {
              code: ErrorCode;
              message: string;
              name?: string;
              details?: Readonly<Record<string, unknown>>;
              retryable: boolean;
              cause?: ErrorPayload;
            };
          };
        };
      };
    };
  };
  durationMs?: number;
}

/**
 * states: turn
 * owner: src/agent/loop/turnOps.ts
 */
interface TurnPromptPayload {
  _name: 'turn.prompt';
  input: readonly ContentPart[];
  /** PromptOrigin */
  origin: 'user' | 'skill_activation' | 'plugin_command' | 'injection' | 'shell_command' | 'compaction_summary' | 'system_trigger' | 'task' | 'cron_job' | 'cron_missed' | 'hook_result' | 'retry';
}

/**
 * states: turn
 * owner: src/agent/loop/turnOps.ts
 */
interface TurnSteerPayload {
  _name: 'turn.steer';
  input: readonly ContentPart[];
  /** PromptOrigin */
  origin: 'user' | 'skill_activation' | 'plugin_command' | 'injection' | 'shell_command' | 'compaction_summary' | 'system_trigger' | 'task' | 'cron_job' | 'cron_missed' | 'hook_result' | 'retry';
}

/**
 * states: usage
 * owner: src/agent/usage/usageOps.ts
 */
interface UsageRecordPayload {
  _name: 'usage.record';
  model: string;
  /** TokenUsage */
  usage: {
    inputOther: number;
    output: number;
    inputCacheRead: number;
    inputCacheCreation: number;
  };
  /** UsageRecordScope */
  usageScope?: 'session' | 'turn';
}

/** Record type → payload sketch. */
interface WirePayloadMap {
  "config.update": ConfigUpdatePayload;
  "context.append_loop_event": ContextAppendLoopEventPayload;
  "context.append_message": ContextAppendMessagePayload;
  "context.apply_compaction": ContextApplyCompactionPayload;
  "context.clear": ContextClearPayload;
  "context.undo": ContextUndoPayload;
  "forked": ForkedPayload;
  "full_compaction.begin": FullCompactionBeginPayload;
  "full_compaction.cancel": FullCompactionCancelPayload;
  "full_compaction.complete": FullCompactionCompletePayload;
  "goal.clear": GoalClearPayload;
  "goal.create": GoalCreatePayload;
  "goal.update": GoalUpdatePayload;
  "interaction.request": InteractionRequestPayload;
  "interaction.resolved": InteractionResolvedPayload;
  "interruptionReminder.recorded": InterruptionReminderRecordedPayload;
  "llm.request": LlmRequestPayload;
  "llm.tools_snapshot": LlmToolsSnapshotPayload;
  "mcp.tools_discovered": McpToolsDiscoveredPayload;
  "permission.record_approval_result": PermissionRecordApprovalResultPayload;
  "permission.set_mode": PermissionSetModePayload;
  "plan_mode.cancel": PlanModeCancelPayload;
  "plan_mode.enter": PlanModeEnterPayload;
  "plan_mode.exit": PlanModeExitPayload;
  "plan.revision": PlanRevisionPayload;
  "plugin.session_start": PluginSessionStartPayload;
  "profile.bind": ProfileBindPayload;
  "prompt.accepted": PromptAcceptedPayload;
  "runtime.set_binding": RuntimeSetBindingPayload;
  "swarm_mode.enter": SwarmModeEnterPayload;
  "swarm_mode.exit": SwarmModeExitPayload;
  "task.started": TaskStartedPayload;
  "task.terminated": TaskTerminatedPayload;
  "token_counting.measured": TokenCountingMeasuredPayload;
  "token_counting.rebased": TokenCountingRebasedPayload;
  "token_counting.truncated": TokenCountingTruncatedPayload;
  "tools.register_user_tool": ToolsRegisterUserToolPayload;
  "tools.reset_active_tools": ToolsResetActiveToolsPayload;
  "tools.set_active_tools": ToolsSetActiveToolsPayload;
  "tools.unregister_user_tool": ToolsUnregisterUserToolPayload;
  "tools.update_store": ToolsUpdateStorePayload;
  "tower_mode.enter": TowerModeEnterPayload;
  "tower_mode.exit": TowerModeExitPayload;
  "turn.cancel": TurnCancelPayload;
  "turn.ended": TurnEndedPayload;
  "turn.prompt": TurnPromptPayload;
  "turn.steer": TurnSteerPayload;
  "usage.record": UsageRecordPayload;
}
